### ISSUE TITLE
Cannot use rspec shared behaviors - `require': cannot load such file -- `rspec`

### ISSUE THREAD

**Issue by thebucknerlife** [slack-ruby/slack-ruby-bot#108]
Hey! Thanks for the great gem first of all.

I'm hoping to test my bot and I can't get rspec to run after I add `require 'slack-ruby-bot/rspec'` to my spec_helper.rb.

Here's the stack trace:

```
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rspec (LoadError)
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/slack-ruby-bot-0.9.0/lib/slack-ruby-bot/rspec.rb:4:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/me/foo/bar-rails-app/spec/spec_helper.rb:101:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `block in requires='
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `each'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `requires='
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:111:in `each'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:99:in `setup'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.4.0/bin/rspec:22:in `load'
	from /usr/local/var/rbenv/versions/2.4.0/bin/rspec:22:in `<main>'
```

Thanks!

**Comment by dblock** [comment]
Care to share some code? [This bot](https://github.com/dblock/slack-gamebot/blob/master/spec/spec_helper.rb#L10) does that without any issues. Have you included slack-ruby-bot in Gemfile?

**Comment by thebucknerlife** [comment]
Gemfile:
```
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem "react_on_rails", "~> 6"
gem 'dotenv-rails', :groups => [:development, :test]
gem "slack-ruby-bot"
gem "celluloid-io"

# other boilerplate...

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'rspec-rails', '~> 3.5'
  gem 'capybara'
  gem 'selenium-webdriver'
end

# ... rest of file
```

and my spec_helper.rb:

```
# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# The `.rspec` file also contains a few flags that are not defaults but that
# users commonly want.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

# The settings below are suggested to provide a good initial experience
# with RSpec, but feel free to customize to your heart's content.
=begin
  # This allows you to limit a spec run to individual examples or groups
  # you care about by tagging them with `:focus` metadata. When nothing
  # is tagged with `:focus`, all examples get run. RSpec also provides
  # aliases for `it`, `describe`, and `context` that include `:focus`
  # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
  config.filter_run_when_matching :focus

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more details, see:
  #   - http://rspec.info/blog/2012/06/rspecs-new-expectation-syntax/
  #   - http://www.teaisaweso.me/blog/2013/05/27/rspecs-new-message-expectation-syntax/
  #   - http://rspec.info/blog/2014/05/notable-changes-in-rspec-3/#zero-monkey-patching-mode
  config.disable_monkey_patching!

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = 'doc'
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed
=end
end

require 'slack-ruby-bot/rspec'
```

This is a new project so almost all boilerplate. Let me know what else would be relevant. Thanks!

**Comment by thebucknerlife** [comment]
I've already built a bot that is working using the `slack-ruby-bot` so it's definitely bundles properly.

**Comment by dblock** [comment]
I put up a link there with identical code that works, so ... can I please have something to `git checkout` that reproduces this and I can take a look ;)

**Comment by thebucknerlife** [comment]
You can go ahead and clone this -> git@github.com:thebucknerlife/slack-bot-bug.git

Copied the codebase and removed some of my work. The app exhibits the same issue when you run `$ rspec`.

Thanks!

**Comment by dblock** [comment]
I can confirm it's a bug. First, `rspec-rails` no longer depends on `rspec`, but on `rspec-core`.

There're actually three dependencies that we're not adding in the slack-ruby-bot gemspec for development/test, `rspec`, `vcr`, and `webmock`. Adding this to your Gemfile will work around it:

```
gem 'rspec'
gem 'vcr'
gem 'webmock'
```

Feel free to PR a fix for this in slack-ruby-bot, too. I'll take care of it otherwise at some point soon.

**Comment by thebucknerlife** [comment]
@dblock this worked, thanks! I'm still not exactly sure how to use the rspec helpers, tho. For example, if my Bot implements a command `chill` to respond with `nice!`, how should I write the test? I have this:

```
require 'rails_helper'
require "#{Rails.root}/bots/my_bot"

RSpec.describe MyBot::Bot do
  describe "chill" do
    it "should response with nice!" do
      # how do I use response_with_slack_message("nice!")
    end
  end
end
```

**Comment by dblock** [comment]
It should be like this: `expect(message: "#{SlackRubyBot.config.user}: chill").to respond_with_slack_message('nice!')`.

**Comment by dblock** [comment]
Documented this in https://github.com/slack-ruby/slack-ruby-bot/pull/115.
