### ISSUE TITLE
Cant open Gem!

### ISSUE THREAD

**Issue by Lalabuy948** [slack-ruby/slack-ruby-bot#124]
## If run 
```
      ruby  bot-start.rb
```

```
.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- simple-slack-bot (LoadError)
```

## If run 

```
       bundle exec ruby bot-start.rb
```

```
slack-bot-start.rb:3:in `require': cannot load such file -- simple-slack-bot (LoadError)
	from slack-bot-start.rb:3:in `<main>'
```

**Comment by dblock** [comment]
What's `simple-slack-bot`? That seems like your code. Post the project and we can help you.

**Comment by dblock** [comment]
@Lalabuy948 care to explain what the problem was for the next person?

**Comment by Lalabuy948** [comment]
@dblock it was another gem, its my mistake
