### ISSUE TITLE
Pushing to heroku fails on v0.7.0

### ISSUE THREAD

**Issue by adamrainsby** [slack-ruby/slack-ruby-bot#60]
It was working on 0.6.0

Could be related to https://github.com/faye/faye-websocket-ruby/issues/80?

```
remote:        Running: rake assets:precompile
remote:        Starting up a new ElasticSearch client with https://atm84j46:xs38h2atn2s9366b@boxwood-6034605.eu-west-1.bonsai.io
remote:        I, [2016-03-24T16:40:25.391736 #793]  INFO -- : post https://slack.com/api/rtm.start
remote:        D, [2016-03-24T16:40:25.394671 #793] DEBUG -- request: Accept: "application/json; charset=utf-8"
remote:        User-Agent: "Slack Ruby Client/0.7.1"
remote:        Content-Type: "application/x-www-form-urlencoded"
remote:        I, [2016-03-24T16:40:26.158368 #793]  INFO -- Status: 200
remote:        D, [2016-03-24T16:40:26.160574 #793] DEBUG -- response: content-type: "application/json; charset=utf-8"
remote:        transfer-encoding: "chunked"
remote:        connection: "close"
remote:        access-control-allow-origin: "*"
remote:        cache-control: "private, no-cache, no-store, must-revalidate"
remote:        content-security-policy: "referrer no-referrer;"
remote:        date: "Thu, 24 Mar 2016 16:40:25 GMT"
remote:        expires: "Mon, 26 Jul 1997 05:00:00 GMT"
remote:        pragma: "no-cache"
remote:        server: "Apache"
remote:        strict-transport-security: "max-age=31536000; includeSubDomains; preload"
remote:        vary: "Accept-Encoding"
remote:        x-accepted-oauth-scopes: "rtm:stream,client"
remote:        x-content-type-options: "nosniff"
remote:        x-oauth-scopes: "identify,read,post,client"
remote:        x-xss-protection: "0"
remote:        x-cache: "Miss from cloudfront"
remote:        via: "1.1 8dae7df87719a07f42e1196c2adda1c1.cloudfront.net (CloudFront)"
remote:        x-amz-cf-id: "FVsd3I5jzLo-PRrNI1CmRH1TY7l5Zm5JEBAVerjBvPfkIozjDGKWiA=="
remote:        D, [2016-03-24T16:40:26.361188 #793] DEBUG -- Slack::RealTime::Concurrency::Eventmachine::Socket#connect!: Slack::RealTime::Concurrency::Eventmachine::Client
remote:        D, [2016-03-24T16:40:26.452678 #793] DEBUG -- Slack::RealTime::Concurrency::Eventmachine::Client#write: GET /websocket/zLN_5Y3pO3MoXLyLkEwDdTzuAI-anlALkOObM5BylUgk2nCSaXQBxAtldAP1bqg6q_2I7pOIdVvqQgL3GmrmpXmqBFZDMbOZr3mQpu_xgb_v6SskVaK1OsSO4a5BbU_YB4idS4fKC3QcgDugsVtwKQ== HTTP/1.1
remote:        Host: mpmulti-hzby.slack-msgs.com
remote:        Upgrade: websocket
remote:        Connection: Upgrade
remote:        Sec-WebSocket-Key: vfz282AWkDZplIzcHW6U5A==
remote:        Sec-WebSocket-Version: 13
remote:        
remote:        D, [2016-03-24T16:40:26.583035 #793] DEBUG -- Slack::RealTime::Concurrency::Eventmachine::Client#parse: HTTP/1.1 101 Switching Protocols
remote:        Upgrade: websocket
remote:        Connection: Upgrade
remote:        Sec-WebSocket-Accept: 1zNNtIeHvGKi6bkEacgF4EzIs9M=
remote:        
remote:        D, [2016-03-24T16:40:26.587803 #793] DEBUG -- SlackRubyBot::Client#run_loop: Faye::WebSocket::API::OpenEvent
remote:  !
remote:  !     invalid byte sequence in UTF-8
remote:  !
remote: /app/tmp/buildpacks/ruby/lib/language_pack/shell_helpers.rb:113:in `split': invalid byte sequence in UTF-8 (ArgumentError)
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/shell_helpers.rb:113:in `puts'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/shell_helpers.rb:94:in `block in pipe'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/shell_helpers.rb:90:in `popen'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/shell_helpers.rb:90:in `pipe'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/helpers/rake_runner.rb:50:in `block in invoke'
remote: 	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/helpers/rake_runner.rb:44:in `invoke'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/rails4.rb:85:in `block (2 levels) in run_assets_precompile_rake_task'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/base.rb:131:in `log'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/rails4.rb:71:in `block in run_assets_precompile_rake_task'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/base.rb:48:in `instrument'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/base.rb:44:in `instrument'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/rails4.rb:70:in `run_assets_precompile_rake_task'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/ruby.rb:104:in `block (2 levels) in compile'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/ruby.rb:767:in `allow_git'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/ruby.rb:98:in `block in compile'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/base.rb:48:in `instrument'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/base.rb:44:in `instrument'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/ruby.rb:88:in `compile'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/rails2.rb:49:in `block in compile'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/base.rb:48:in `instrument'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/base.rb:44:in `instrument'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/rails2.rb:47:in `compile'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/rails3.rb:38:in `block in compile'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/base.rb:48:in `instrument'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/base.rb:44:in `instrument'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/rails3.rb:37:in `compile'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/rails4.rb:41:in `block in compile'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/base.rb:48:in `instrument'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/base.rb:44:in `instrument'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/rails4.rb:40:in `compile'
remote: 	from /app/tmp/buildpacks/ruby/bin/compile:16:in `block (2 levels) in <main>'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/base.rb:131:in `log'
remote: 	from /app/tmp/buildpacks/ruby/bin/compile:15:in `block in <main>'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:35:in `block in trace'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /app/tmp/buildpacks/ruby/lib/language_pack/instrument.rb:35:in `trace'
remote: 	from /app/tmp/buildpacks/ruby/bin/compile:11:in `<main>'
remote: 
remote:  !     Push rejected, failed to compile Ruby app
remote: 
```

**Comment by dblock** [comment]
I am not sure that would fix the problem, but `rake assets:precompile` shouldn't be starting your bot AFAIK. Try running that locally, do you get the same error by any chance?

**Comment by PenguinGabe** [comment]
hi i'm facing the same problem - any updates on the fix?

**Comment by Waffleboy** [comment]
Same problem.

**Comment by dblock** [comment]
Looking at this closer the log level is too verbose and is trying to dump a bunch of information on the console and fails for binary data. Reduce it?

```ruby
SlackRubyBot::Client.logger.level = Logger::WARN
```

It should spit a lot less than this. Can @PenguinGabe / @Waffleboy give it a try?

**Comment by chao-xian** [comment]
I was seeing this same problem and switched from celluloid-io to faye-websocket and now it works!

**Comment by chao-xian** [comment]
Ah sorry I didn't spot that OP referenced faye so is probably using faye in the first place. I was seeing the same errors though with celluloid-io.

**Comment by dblock** [comment]
@chao-xian Silencing loggers will work.

**Comment by chao-xian** [comment]
Hi @dblock I stuck that config you suggested in production.rb but I was still seeing the error on heroku but that may well have been the wrong place to put it.

**Comment by dblock** [comment]
Did it change the logger level? Are you still seeing things like `remote:        D, [2016-03-24T16:40:26.160574 #793] DEBUG -- response:`? 

Can someone build me a quick repro that I can try?

**Comment by chao-xian** [comment]
@dblock Ah yes it did change the log level - stopped seeing response etc as you say (below). You can try https://github.com/chao-xian/marvelbot but with celluloid-io instead of faye-websocket (so previous commit).

My error mentioned celluloid whereas @adamrainsby's didn't which is what led me to switch. But I was seeing the same sort of failure around asset pre-compilation, also with the UTF-8 message (before lowering the log level).

```
remote:        Bundle completed (41.27s)
remote:        Cleaning up the bundler cache.
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        I, [2016-08-24T20:23:32.902317 #1247]  INFO -- : Celluloid 0.17.3 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
remote:        I, [2016-08-24T20:23:33.483577 #1247]  INFO -- : Successfully connected to https://thecomicbookclub.slack.com.
remote:        I, [2016-08-24T20:23:35.898397 #1247]  INFO -- : Writing /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/public/assets/application-12006f97c59529ad7801f7c7b1ea6d03b973c67d135af5f60c22b0ad1531190b.js
remote:        I, [2016-08-24T20:23:35.899408 #1247]  INFO -- : Writing /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/public/assets/application-12006f97c59529ad7801f7c7b1ea6d03b973c67d135af5f60c22b0ad1531190b.js.gz
remote:        I, [2016-08-24T20:23:35.910360 #1247]  INFO -- : Writing /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/public/assets/application-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.css
remote:        I, [2016-08-24T20:23:35.910828 #1247]  INFO -- : Writing /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/public/assets/application-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.css.gz
remote:        ERROR: task was terminated
remote:        /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:35:in `terminate'
remote:        /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:323:in `block in cleanup'
remote:        /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:321:in `each'
remote:        /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:321:in `cleanup'
remote:        /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:307:in `shutdown'
remote:        /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:169:in `run'
remote:        /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'
remote:        /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
remote:        /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
remote:        /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `call'
remote:        /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
remote:        (celluloid):0:in `remote procedure call'
remote:        /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
remote:        /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
remote:        /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/slack-ruby-client-0.7.6/lib/slack/real_time/client.rb:51:in `start!'
remote:        /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/slack-ruby-bot-0.8.2/lib/slack-ruby-bot/server.rb:37:in `start!'
remote:        /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/slack-ruby-bot-0.8.2/lib/slack-ruby-bot/server.rb:29:in `block (2 levels) in run'
remote:        /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/slack-ruby-bot-0.8.2/lib/slack-ruby-bot/server.rb:69:in `handle_exceptions'
remote:        /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/slack-ruby-bot-0.8.2/lib/slack-ruby-bot/server.rb:27:in `block in run'
remote:        /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/slack-ruby-bot-0.8.2/lib/slack-ruby-bot/server.rb:26:in `loop'
remote:        /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/slack-ruby-bot-0.8.2/lib/slack-ruby-bot/server.rb:26:in `run'
remote:        /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/bot/tattletale.rb:8:in `block in <top (required)>'
remote:        /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:35:in `terminate': task was terminated (Celluloid::TaskTerminated)
remote:        from /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:323:in `block in cleanup'
remote:        from /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:321:in `each'
remote:        from /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:321:in `cleanup'
remote:        from /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:307:in `shutdown'
remote:        from /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:169:in `run'
remote:        from /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'
remote:        from /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
remote:        from /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
remote:        from /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `call'
remote:        from /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
remote:        from (celluloid):0:in `remote procedure call'
remote:        from /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
remote:        from /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
remote:        from /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/slack-ruby-client-0.7.6/lib/slack/real_time/client.rb:51:in `start!'
remote:        from /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/slack-ruby-bot-0.8.2/lib/slack-ruby-bot/server.rb:37:in `start!'
remote:        from /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/slack-ruby-bot-0.8.2/lib/slack-ruby-bot/server.rb:29:in `block (2 levels) in run'
remote:        from /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/slack-ruby-bot-0.8.2/lib/slack-ruby-bot/server.rb:69:in `handle_exceptions'
remote:        from /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/slack-ruby-bot-0.8.2/lib/slack-ruby-bot/server.rb:27:in `block in run'
remote:        from /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/slack-ruby-bot-0.8.2/lib/slack-ruby-bot/server.rb:26:in `loop'
remote:        from /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/vendor/bundle/ruby/2.2.0/gems/slack-ruby-bot-0.8.2/lib/slack-ruby-bot/server.rb:26:in `run'
remote:        from /tmp/build_9281f46a7d70a99c3bfb3ef7000e1044/bot/tattletale.rb:8:in `block in <top (required)>'
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to marvelbot.
remote:
To https://git.heroku.com/marvelbot.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/marvelbot.git'
```

**Comment by dblock** [comment]
Ok, for rails `config/initializers` is just not the right place to put bot startup code. Move it to config.ru like I did in https://github.com/slack-ruby/slack-bot-on-rails/pull/1.

**Comment by dblock** [comment]
@chao-xian Do you want to contribute a Heroku button install to https://github.com/slack-ruby/slack-bot-on-rails? This way we can make sure the generic demo project works first and see if it works for your own?

**Comment by dblock** [comment]
This is resolved, closing.
